version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"       # <-- important: points to the frontend folder
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # optionally add `allow`/`ignore` blocks to tune deps
