from pydantic import BaseModel, EmailStr, validator, field_validator
from typing import Optional

class Restaurant(BaseModel):
    restaurant_id: Optional[int] = None  # Auto-generated by DB
    name: str
    description: Optional[str] = None
    address: str
    phone: str
    email: EmailStr
    cuisine_type: str
    is_active: bool = True
    rating: Optional[float] = 0.0
    delivery_fee: Optional[float] = 0.0

    class Config:
        populate_by_name = True  # Allow both snake_case and PascalCase
        # For Pydantic v1, use alias_generator to preserve field names
        # But we'll set it via fields instead

class RestaurantCreate(BaseModel):
    name: str
    description: Optional[str] = None
    address: str
    phone: str
    email: EmailStr
    cuisine_type: str
    delivery_fee: Optional[float] = 0.0
    
    @field_validator('delivery_fee')
    @classmethod
    def validate_delivery_fee(cls, v):
        if v is not None and v < 0:
            raise ValueError('Delivery fee cannot be negative')
        return v
    
    class Config:
        populate_by_name = True