from pydantic import BaseModel, EmailStr
from typing import Optional

class Restaurant(BaseModel):
    RestaurantId: Optional[int] = None  # Auto-generated by DB
    Name: str
    Description: Optional[str] = None
    Address: str
    Phone: str
    Email: EmailStr
    CuisineType: str
    IsActive: bool = True
    Rating: Optional[float] = 0.0
    DeliveryFee: Optional[float] = 0.0

class RestaurantCreate(BaseModel):
    Name: str
    Description: Optional[str] = None
    Address: str
    Phone: str
    Email: EmailStr
    CuisineType: str
    DeliveryFee: Optional[float] = 0.0