from pydantic import BaseModel, EmailStr, field_validator
from typing import Optional

class Restaurant(BaseModel):
    RestaurantId: Optional[int] = None  # Auto-generated by DB
    Name: str
    Description: Optional[str] = None
    Address: str
    Phone: str
    Email: EmailStr
    CuisineType: str
    IsActive: bool = True
    Rating: Optional[float] = 0.0
    DeliveryFee: Optional[float] = 0.0

class RestaurantCreate(BaseModel):
    Name: str
    Description: Optional[str] = None
    Address: str
    Phone: str
    Email: EmailStr
    CuisineType: str
    DeliveryFee: Optional[float] = 0.0
    
    @field_validator('DeliveryFee')
    @classmethod
    def validate_delivery_fee(cls, v):
        if v is not None and v < 0:
            raise ValueError('Delivery fee cannot be negative')
        return v