name: Code Quality 🔍

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: code-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-quality:
    name: Frontend Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: TypeScript type check
        run: npm run type-check
        working-directory: ./frontend

      - name: ESLint check
        run: npm run lint
        working-directory: ./frontend

      - name: Prettier format check
        run: npm run format:check
        working-directory: ./frontend